# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 700
palette = "everforest"

# Replace the 'â¯' symbol in the prompt with 'âœ'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ](bold red)'


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

format="""$all"""

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘ï¸ '

# This is the default symbols table.

[os]
disabled = false
style = "bold blue"

[hostname]
ssh_only = false
style = 'fg:blue'

[directory]
style = "fg:orange"
read_only_style = "fg:orange"

[git_branch]
style = "fg:green"

[palettes.everforest]
bg_dim = "#232a2e"
bg0 = "#2d353b"
bg1 = "#343f44"
bg2 = "#3d484d"
bg3 = "#475258"
bg4 = "#4f585e"
bg5 = "#56635f"
bg_visual = "#543a48"
bg_red = "#514045"
bg_green = "#425047"
bg_blue = "#3a515d"
bg_yellow = "#4d4c43"

fg = "#d3c6aa"
red = "#e67e80"

orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"
statusline1 = "#a7c080"
statusline2 = "#d3c6aa"
statusline3 = "#e67e80"

[palettes.yugen]
bg_dim = "#000000"
bg0 = "#151515"
bg1 = "#303030"
bg2 = "#505050"
bg3 = "#696969"
bg4 = "#A9A9A9"
bg5 = "#D4D4D4"

bg_visual = "#303030"
bg_red = "#2A1A1A"
bg_green = "#1A2A1A"
bg_blue = "#1A1A2A"
bg_yellow = "#2A2A1A"

fg = "#D2D2D2"

red = "#F57A7A"
orange = "#FFBE89"
yellow = "#FFF2AF"
green = "#7EAB8E"
aqua = "#89BEFF"
blue = "#89BEFF"
purple = "#BE89FF"

grey0 = "#505050"
grey1 = "#696969"
grey2 = "#A9A9A9"

statusline1 = "#FFBE89"
statusline2 = "#FAFAFA"
statusline3 = "#D2D2D2"

[conda]
ignore_base = true

[battery]
disabled = true

# ~/.config/starship.toml
