font.size = 11

[font.normal]
family = "JetBrains Mono"

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
startup_mode = "Maximized"
decorations = "None"
# opacity = 0.6
# blur = true

[terminal.shell]
program = "/sbin/zsh"
args = ["-l", "-c", "tmux -u attach-session -t master || tmux -u new-session -s master; exec /sbin/zsh"]

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  #  "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
   # "~/.config/alacritty/themes/atom-one-dark.toml"
  "~/.config/alacritty/themes/everforest.toml"
  # "~/.config/alacritty/themes/tokyonight-night.toml"
  # "~/.config/alacritty/themes/coolnight.toml"
  # "~/.config/alacritty/themes/yugen.toml"
]
